In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr

samples = np.random.randn(2, 3)    
    
data = xr.DataArray(samples, name='NDVI',
                        dims=('x', 'y'),
                        coords={'x': [10, 20]})

data


<xarray.DataArray 'NDVI' (x: 2, y: 3)>
array([[ 0.034113,  0.030692, -0.8512  ],
       [-1.331127, -0.651142, -1.958462]])
Coordinates:
  * x        (x) int32 10 20
Dimensions without coordinates: y

In [6]:

# checando coordenadas (mesmo que sem dimensões)

data.coords['y']

a = xr.DataArray(np.random.randn(3), coords=[data.coords['y']])

In [7]:
# broadcasting operações aritméticas baseadas em nomes de dimensões:

b = xr.DataArray(np.random.randn(4), dims='z')

In [8]:
a+ b

<xarray.DataArray (y: 3, z: 4)>
array([[ 2.603665,  2.675038,  1.614126, -0.721742],
       [ 2.06547 ,  2.136843,  1.075932, -1.259937],
       [ 0.388176,  0.459549, -0.601362, -2.937231]])
Coordinates:
  * y        (y) int64 0 1 2
Dimensions without coordinates: z

In [9]:
# PORTANTO, NÃO PRECISAMOS NOS PREOCUPAR COM A ORDEM DAS OPERAÇÕES:

data - data.T

<xarray.DataArray 'NDVI' (x: 2, y: 3)>
array([[0., 0., 0.],
       [0., 0., 0.]])
Coordinates:
  * x        (x) int32 10 20
Dimensions without coordinates: y