In [2]:
import numpy as np

from osgeo import gdal

from osgeo import osr

from gdalconst import *

gdal.UseExceptions()

import sys

filename = r"C:\Users\Philipe Leal\Python\exercicios\focos\focos_aula11.tif"

#abrindo um arquivo raster formato tiff pelo Gdal, em modo "leitura apenas" = Read Only

dataset = gdal.Open(filename, GA_ReadOnly)


# dataset = none 

# fechar o dataset e liberar memória

In [2]:
#loop ver verificação de coerência do programa. Caso ocorra algum erro ou do diretório (arquivos corrompidos, ou programa deu pau)
#Neste caso, a função abaixo diz, verifique se OK. Se Erro, fechar o programa.

#Opção 2 seria. Caso erro, pular arquivo corrompido. Ver 

try:
    dataset = gdal.Open(filename, GA_ReadOnly)
    print("Arquivo Aberto com sucesso!")
except RuntimeError, e:
    print e
    sys.exit("Erro na abertura do arquivo")
    pass

Arquivo Aberto com sucesso!


In [3]:
#Manipulação do DATASET: pode conter n dimensões. Indico usar como um array. Vai ter sempre o mesmo número de linhas e colunas do arquivo inicial.

# a partir de um dataset é possível verificar propriedades de um dataset. Ex: coordenadas da janela, N° de linha e colunas, resolução espacial etc.

# a função Geotransform tem os seguintes parâmetros na seguinte sequência

    # coordenada do pixel em x no canto superior esquerdo
    #resolução do pixel em X Leste-Oeste
    #Rotação no eixo X (Normalmente 0.0)
    #Coordenada do pixel em Y  no canto superior esquerdo
    #Rotação no exio Y (normalmente 0.0)
    #Resoluão do píxel em Y (valor negativo)

In [4]:
print dataset.GetGeoTransform()

(-83.005, 0.01, 0.0, 13.005, 0.0, -0.01)


In [5]:
# Exercício 2 - Escrever um programa para verificar valores de latitude inicial, longitude inicial e resolução espacial

# dica para a formatação de numeros na apresentação:

    #opção 1
variavel = 1
str(variavel).zfill(3)

    # opção 2 para dição de zeros antes do nome/valor da variavel

"%03d"%variavel
    
    #opção 3 para adição de zeros
print("{0:03d}").format(variavel)


001


In [6]:
#Teste da funcao Zfill para uma variável já com 3 caracteres

variavel = 543
str(variavel).zfill(3)



'543'

In [7]:
Transform = dataset.GetGeoTransform()
Latitude_inicial = Transform [3]
Longitude_inicial = Transform [0]
Resolucao = Transform [1]

In [8]:
# notar que ao utilizar a função %o3d para formatação do nome do arquivo, perde-se o sinal negativo da variável.
#notar que o \t serve para tabular bonitinho um print

print("Latitude inicial - canto superior esquerdo: \t %03d" %Latitude_inicial)
print("Longitude inicial - canto superior esquerdo: \t %03d" %Latitude_inicial)
print("a resolução do dataset é: \t %03d" %Resolucao)
# o mesmo ocorre ao se utilizar da função zfill

Latitude inicial - canto superior esquerdo: 	 013
Longitude inicial - canto superior esquerdo: 	 013
a resolução do dataset é: 	 000


In [9]:
#Dimensoes do arquivo: para saber o número de linhas e colunas do dataset.


print(dataset.RasterXSize, dataset.RasterYSize)



(5000, 6300)


In [10]:
caminho_arquivo = "C:\Users\Philipe Leal\Python\landsat/LC82210742016203LGN00.jpg"
dataset = gdal.Open(caminho_arquivo, GA_ReadOnly)

for banda in range(dataset.RasterCount):
    print("Leitura da Banda %s" %(banda+1))


Leitura da Banda 1
Leitura da Banda 2
Leitura da Banda 3


In [11]:
banda1 = dataset.GetRasterBand(1)
banda2 = dataset.GetRasterBand(2)
banda3 = dataset.GetRasterBand(3)

In [12]:
#Observar que se utilizada a função acima com a  alteração da dimensão da banda para 2, as leituras das bandas diminuem:

caminho_arquivo = "C:\Users\Philipe Leal\Python\landsat/LC82210742016203LGN00.jpg"
dataset = gdal.Open(caminho_arquivo, GA_ReadOnly)

for banda in range(2):
    print("Leitura da Banda %s" %(banda+1))

Leitura da Banda 1
Leitura da Banda 2


In [13]:
caminho_arquivo = "C:\Users\Philipe Leal\Python\landsat/LC82210742016203LGN00.jpg"
dataset = gdal.Open(caminho_arquivo, GA_ReadOnly)

if dataset.RasterCount ==3:
    banda1 = dataset.GetRasterBand(1)
    banda2 = dataset.GetRasterBand(2)
    banda3 = dataset.GetRasterBand(3)

In [14]:
#Função de verificação do tipo do arquivo

print(gdal.GetDataTypeName(banda1.DataType))

#É possível saber qual o valor mínimo e máximo de uma banda utilizadno o método da banda ComputeRaster Min Min

(min, max) = banda1.ComputeRasterMinMax()
print(min, max)

Byte
(0.0, 221.0)


# Exercício 5 - Escrevendo uma parte de código para apresentar os valores de estatística de cada banda do arquivo, apresentação formatada e mostrando o nome  da banda. Valores min, max com duas casas decimais depois da vírgula

print (Calcula estatística da Banda 1)

banda1.ComputeRasterMinMax()[0]


In [15]:
print ("Calcula estatística da Banda 1")
banda1.ComputeRasterMinMax()[0]
    
      


Calcula estatística da Banda 1


0.0

In [16]:
# print("mínimo da Banda 1 = %02f" %banda1.ComputeRasterMinMax()[0] # não funciona

# print("mínimo da Banda 1 = banda1.ComputeRasterMinMax()[0] + 0.00 # não funciona
      
print("mínimo da Banda 1 = %0.2f" %(banda1.ComputeRasterMinMax()[0]))

print("mínimo da Banda 2 = %0.2f" %(banda2.ComputeRasterMinMax()[0]))  

print("mínimo da Banda 3 = %0.2f" %(banda3.ComputeRasterMinMax()[0]))

mínimo da Banda 1 = 0.00
mínimo da Banda 2 = 0.00
mínimo da Banda 3 = 0.00


In [17]:
print("max da Banda 1 = %0.2f" %(banda1.ComputeRasterMinMax()[1]))

print("max da Banda 2 = %0.2f" %(banda2.ComputeRasterMinMax()[1]))  

print("max da Banda 3 = %0.2f" %(banda3.ComputeRasterMinMax()[1]))

max da Banda 1 = 221.00
max da Banda 2 = 225.00
max da Banda 3 = 202.00


In [18]:
print("O mínimo da Banda 1 é %0.2f, e o máx é %0.2f" %(banda1.ComputeRasterMinMax()[0], banda1.ComputeRasterMinMax()[1]))

print("O mínimo da Banda 2 é %0.2f, e o máx é %0.2f" %(banda2.ComputeRasterMinMax()[0], banda2.ComputeRasterMinMax()[1]))

O mínimo da Banda 1 é 0.00, e o máx é 221.00
O mínimo da Banda 2 é 0.00, e o máx é 225.00


# Depois de criado o objeto banda precisamos ler os dados para iniciar qualquer processamento com estes valores. Uma maneira utilizada é manipular os dados matriciais com auxílio da biblioteca NUMPY. O próprio GDAL posui o método ReadAsArray para leitura dos valores gerando uma array multidimensional, veja o exemplo:

In [19]:
arr_b1 = banda1.ReadAsArray()

print(type(arr_b1))


<type 'numpy.ndarray'>


In [20]:
# Função shape do Num Py

print arr_b1.shape

(7841L, 7721L)


In [21]:
soma = arr_b1 + arr_b1

soma

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [22]:
#como saber quantos píxeis não zero estão presentes no arr_b1?

print (np.count_nonzero(arr_b1))

41896420


# para determinar a coordenada de qualquer píxel em um arquivo raster, deve-se utilizar de uma transformação linear da seguinte maneira:

Latitude = Linha*resolução Y +latitude inicial + (resolução Y * 0.5)

Longitude = coluna * resolução X + longitude inicial + (resolução X *0.5)

Notar que foi adiionado (resolução*0.5) aos valores estimados, pois a GDAL indica o canto do píxel e desta maneira podemos indicar a coordenada do centro de um píxel



# Exercício 5 - Utilizando o dado da Quantidade de focos acumulados no ano, escreva um programa para apresentar o valor de cada célula diferente de zero, longitude e latitude.

In [23]:
idx = np.nonzero(arr_b1)

len(idx[0]) #Linhas
#np.unique (idx[0])


41896420

In [24]:
filename = r"C:\Users\Philipe Leal\Python\exercicios\focos\focos_aula11.tif"

In [25]:
dataset = gdal.Open(filename, GA_ReadOnly)

In [26]:
banda1 = dataset.GetRasterBand(1)

In [27]:
arr_b1 = banda1.ReadAsArray()

print(arr_b1)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [28]:
arr_b1

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int16)

In [29]:
#Neste caso, lembrar que a função np.where retorna uma tupla de 2 dimensões. A primeira é longitude (x), e a segunda é latitude (y)


idx = np.where(arr_b1 > 0)

In [30]:
#Como saber quantos píxeis não zero estão neste arquivo:

len(idx[0])

35172

In [31]:
#outra forma de fazer isso é através da função np.nonzero(), que também retorna um índice dos píxeis com valores para uma data condição - no caso, > 0.

print(np.nonzero(arr_b1))

print("")
print("Número de píxeis com fogo ={0} ".format(len(idx[0])))

(array([ 126,  126,  126, ..., 6174, 6288, 6289], dtype=int64), array([1279, 1280, 1281, ..., 1013, 1081, 1081], dtype=int64))

Número de píxeis com fogo =35172 


In [32]:
#Sistema de chaves como indicador/procurador de coordenadas

print (arr_b1[3, 3]) #retorna o valor do píxel na posição (3, 3)

print("")

print (arr_b1[:3, :3]) #Retorna uma matriz de píxeis 3:3, começando pelo píxel (1, 1) da array_b1

print("")

print(arr_b1[ 1:4, 1:4]) #Retorna uma matriz de píxeis 3:3, começando pelo píxel (2, 2) da array_b1, chegando até a posição 4:4

0

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [33]:
for i in idx[0]:
    print(i)

126
126
126
126
127
127
136
137
137
138
138
163
163
164
165
168
170
170
171
171
171
172
174
174
176
176
177
177
177
178
180
180
181
181
181
182
185
185
185
186
189
189
190
190
191
191
191
192
192
193
193
193
193
194
194
194
194
195
195
195
196
196
196
196
196
197
197
197
197
198
198
199
199
200
200
200
200
201
201
202
202
202
202
202
202
202
204
204
204
204
205
205
205
205
206
206
206
206
207
207
208
208
208
209
209
209
209
209
210
210
210
210
211
211
211
212
212
213
213
213
214
214
214
214
215
215
215
215
216
216
216
216
216
216
216
217
217
217
217
218
218
219
219
219
219
219
220
220
220
220
220
220
220
221
221
221
221
222
222
222
222
222
222
223
223
225
225
225
225
226
226
226
226
226
226
227
227
227
227
228
228
228
228
228
228
228
228
228
228
228
229
229
229
229
229
230
230
230
230
231
231
232
233
234
234
235
235
236
236
237
237
237
238
238
239
239
240
240
240
240
241
242
242
242
242
242
242
243
243
243
243
243
244
244
244
244
244
244
245
245
245
245
245
245
245
246
246
246
246
247


In [34]:
Linhas = idx[0]

len(Linhas)

35172

In [36]:
for numero in range(len(Linhas)): #varrendo cada linha do idx
    print "Linha : %s" %Linhas[numero]
    print "coluna: %s" %idx[1][numero]
    print "valor do pixel %s\n" % arr_b1[Linhas[numero], idx[1][numero]]
    print()

Linha : 126
coluna: 1279
valor do pixel 1

Linha : 126
coluna: 1280
valor do pixel 7

Linha : 126
coluna: 1281
valor do pixel 4

Linha : 126
coluna: 1282
valor do pixel 2

Linha : 127
coluna: 1280
valor do pixel 4

Linha : 127
coluna: 1281
valor do pixel 3

Linha : 136
coluna: 1279
valor do pixel 1

Linha : 137
coluna: 1278
valor do pixel 3

Linha : 137
coluna: 1279
valor do pixel 8

Linha : 138
coluna: 1278
valor do pixel 6

Linha : 138
coluna: 1279
valor do pixel 5

Linha : 163
coluna: 992
valor do pixel 1

Linha : 163
coluna: 993
valor do pixel 1

Linha : 164
coluna: 1039
valor do pixel 1

Linha : 165
coluna: 1323
valor do pixel 1

Linha : 168
coluna: 988
valor do pixel 1

Linha : 170
coluna: 984
valor do pixel 1

Linha : 170
coluna: 985
valor do pixel 1

Linha : 171
coluna: 1399
valor do pixel 1

Linha : 171
coluna: 1400
valor do pixel 1

Linha : 171
coluna: 1430
valor do pixel 1

Linha : 172
coluna: 980
valor do pixel 1

Linha : 174
coluna: 981
valor do pixel 1

Linha : 174
coluna